platform: linux
inputs:
  - name: binary-builder
  - name: buildpacks-ci
params:
  SPEC_NAMES:
run:
  path: bash
  args:
    - '-cl'
    - 'buildpacks-ci/tasks/check-for-binary-builder-integration-spec-presence/run.rb'
