---
platform: linux

inputs:
  - name: buildpacks-ci
  - name: brats
  - name: cf-environments
run:
  path: buildpacks-ci/tasks/run-brats/run.sh
params:
  BRATS_BRANCH:
  CI_CF_USERNAME:
  CI_CF_PASSWORD:
  LANGUAGE:
  RUBYGEM_MIRROR:
  BOSH_LITE_DOMAIN_NAME:
