platform: linux

inputs:
  - name: binary-builder
  - name: buildpacks-ci
params:
  SPEC_TO_RUN:
  RUN_ORACLE_PHP_TESTS: false
  RUBYGEM_MIRROR:
  AWS_ACCESS_KEY:
  AWS_SECRET_ACCESS_KEY:
  BINARY_BUILDER_PLATFORM:
run:
  path: buildpacks-ci/scripts/binary-builder-integration.sh
