platform: ppc64le

image_resource:
  type: docker-image
  source:
    repository: 140.211.168.31:5000/cloudfoundry/cflinuxfs2
    insecure_registries: ["140.211.168.31:5000"]
inputs:
  - name: binary-builder
  - name: buildpacks-ci
params:
  TOTAL_GROUPS: 1
  CURRENT_GROUP: 1
run:
  path: buildpacks-ci/scripts/binary-builder.sh

