---
platform: linux

inputs:
  - name: binary-builder
  - name: buildpacks-ci
  - name: builds-yaml
  - name: built-yaml
outputs:
  - name: binary-builder-artifacts
  - name: builds-yaml-artifacts
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/scripts/build-binary.rb
params:
  RUBYGEM_MIRROR:
  BINARY_BUILDER_PLATFORM:
  BINARY_BUILDER_OS_NAME:
