---
platform: linux

inputs:
  - name: buildpack-artifacts
    path: buildpack
  - name: buildpacks-ci
  - name: cf-environments
run:
  path: buildpacks-ci/scripts/test_buildpack
params:
  COMPOSER_GITHUB_OAUTH_TOKEN:
  STACKS:
  CF_PASSWORD:
  RUBYGEM_MIRROR:
