---
platform: linux

inputs:
  - name: buildpacks-ci
  - name: buildpack
outputs:
  - name: updated-buildpack
run:
  path: bash
  args:
    - -c
    - "cd buildpack && ./bin/populate-modules-in-manifest && (git commit -am 'Updated manifest with supported PHP modules [ci skip]' || true) && cd - && rsync -a buildpack/ updated-buildpack"
