resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/barthy1/buildpacks-ci
      branch: power-support
      paths: [ "Dockerfile.ppc64le", "build/*"]
  - name: buildpacks-ci-image
    type: docker-image
    source:
      repository: 140.211.168.97:5000/buildpacks/ci
      insecure_registries: ["140.211.168.97:5000"]
      username: {{username}}
      password: {{password}}
jobs:
  - name: ci-build
    serial: true
    plan:
      - get: buildpacks-ci
        trigger: true
      - put: buildpacks-ci-image
        params:
          build: buildpacks-ci
          dockerfile: buildpacks-ci/Dockerfile.ppc64le
          push: true
