---
platform: linux

inputs:
  - name: pivotal-buildpack
  - name: pivotal-buildpack-cached
  - name: buildpacks-ci
  - name: buildpack
outputs:
  - name: buildpack-artifacts
run:
  path: bash
  args:
    - -c
    - |
      set -e
      pushd buildpacks-ci
        tasks/detect-and-upload/run.rb
      popd
params:
  RUBYGEM_MIRROR:
