#!/bin/bash

echo BEFORE WRAPPER
cat << EOF > /bin/wrapper
#!/usr/bin/env ruby
puts 'a'
puts system('source /etc/profile.d/filter.sh')
puts 'b'
exec(*ARGV)
EOF

chmod +x /bin/wrapper

cat /bin/wrapper

pushd buildpacks-ci
  echo BEFORE WRAPPER INVOCATION
  /bin/wrapper ./scripts/stacks/test-ruby
  echo AFTER WRAPPER INVOCATION
  printenv
popd
