#!/bin/bash

echo BEFORE WRAPPER
cat << EOF > /bin/wrapper
#!/usr/bin/env ruby
puts 'a'
ENV['TEST'] = 22222
exec("/usr/bin/env", "bash", "-c", "source /etc/profile.d/filter.sh")
puts 'b'
exec(*ARGV)
EOF

chmod +x /bin/wrapper

cat /bin/wrapper
cat /etc/profile.d/filter.sh

pushd buildpacks-ci
  echo BEFORE WRAPPER INVOCATION
  export TEST=123
  . /bin/wrapper ./scripts/stacks/test-ruby
  echo AFTER WRAPPER INVOCATION
  printenv
popd
