#!/bin/bash

echo BEFORE WRAPPER
cat << EOF > /bin/wrapper
#!/usr/bin/env ruby
puts 'a'
exec("/usr/bin/env", "bash", "-c", "source /bin/tap")
puts 'b'
exec(*ARGV)
EOF

echo BEFORE WRAPPER
cat << EOF > /bin/tap
#!/usr/bin/env bash
export TEST=22222
EOF


chmod +x /bin/wrapper
chmod +x /bin/tap

cat /bin/wrapper
cat /etc/profile.d/filter.sh

pushd buildpacks-ci
  echo BEFORE WRAPPER INVOCATION
  export TEST=123
  . /bin/wrapper ./scripts/stacks/test-ruby
  echo AFTER WRAPPER INVOCATION
  printenv
popd
