---
platform: linux

inputs:
  - name: buildpack-artifacts
    path: buildpack
  - name: buildpacks-ci
  - name: cf-environments
run:
  path: buildpacks-ci/tasks/run-buildpack-specs/run.sh
params:
  COMPOSER_GITHUB_OAUTH_TOKEN:
  STACKS:
  CF_PASSWORD:
  RUBYGEM_MIRROR:
  BOSH_LITE_DOMAIN_NAME:
  DEPLOYMENT_NAME1:
  DOMAIN_NAME:
